version: "3"
services:
  redis:
    image: redis:7-alpine

  api:
    image: 617893088694.dkr.ecr.ap-northeast-1.amazonaws.com/shopping-mall-go:latest
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - DB_SOURCE=postgresql://postgres:lScagw1wOoHlroKNUBEv@shopping-mall.c4l5ilqti7tc.ap-northeast-1.rds.amazonaws.com:5432/shopping_mall
      - REDIS_ADDRESS=redis:6379
