version: "3"
services:
  # postgres:
  #   image: postgres:15.3-alpine
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=password
  #     - POSTGRES_DB=shopping_mall

  redis:
    image: redis:7-alpine

  api:
    image: 617893088694.dkr.ecr.ap-northeast-1.amazonaws.com/shopping-mall-go:latest
    ports:
      - "8080:8080"
    depends_on:
      # - postgres
      - redis
    environment:
      - DB_SOURCE=postgresql://postgres:lScagw1wOoHlroKNUBEv@shopping-mall.c4l5ilqti7tc.ap-northeast-1.rds.amazonaws.com:5432/shopping_mall
      - REDIS_ADDRESS=redis:6379
    entrypoint: ["/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh"]
    command: ["/app/main"]
