// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: admin_account_role.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAdminUserRole = `-- name: CreateAdminUserRole :one
INSERT INTO admin_user_roles (
  admin_user_id,
  role_id
)
VALUES (
  $1, $2
) RETURNING admin_user_id, role_id
`

type CreateAdminUserRoleParams struct {
	AdminUserID pgtype.Int4 `json:"admin_user_id"`
	RoleID      pgtype.Int4 `json:"role_id"`
}

func (q *Queries) CreateAdminUserRole(ctx context.Context, arg CreateAdminUserRoleParams) (AdminUserRole, error) {
	row := q.db.QueryRow(ctx, createAdminUserRole, arg.AdminUserID, arg.RoleID)
	var i AdminUserRole
	err := row.Scan(&i.AdminUserID, &i.RoleID)
	return i, err
}

const deleteAdminUserRoleByAdminUserId = `-- name: DeleteAdminUserRoleByAdminUserId :exec
DELETE FROM admin_user_roles
WHERE admin_user_id = $1
`

func (q *Queries) DeleteAdminUserRoleByAdminUserId(ctx context.Context, adminUserID pgtype.Int4) error {
	_, err := q.db.Exec(ctx, deleteAdminUserRoleByAdminUserId, adminUserID)
	return err
}

const deleteAdminUserRoleByRoleId = `-- name: DeleteAdminUserRoleByRoleId :exec
DELETE FROM admin_user_roles
WHERE role_id = $1
`

func (q *Queries) DeleteAdminUserRoleByRoleId(ctx context.Context, roleID pgtype.Int4) error {
	_, err := q.db.Exec(ctx, deleteAdminUserRoleByRoleId, roleID)
	return err
}

const getAdminUserRole = `-- name: GetAdminUserRole :one
SELECT admin_user_id, role_id FROM admin_user_roles
WHERE admin_user_id = $1 AND role_id = $2
LIMIT 1
`

type GetAdminUserRoleParams struct {
	AdminUserID pgtype.Int4 `json:"admin_user_id"`
	RoleID      pgtype.Int4 `json:"role_id"`
}

func (q *Queries) GetAdminUserRole(ctx context.Context, arg GetAdminUserRoleParams) (AdminUserRole, error) {
	row := q.db.QueryRow(ctx, getAdminUserRole, arg.AdminUserID, arg.RoleID)
	var i AdminUserRole
	err := row.Scan(&i.AdminUserID, &i.RoleID)
	return i, err
}

const listAdminUserRoleByAdminUserId = `-- name: ListAdminUserRoleByAdminUserId :many
SELECT admin_user_id, role_id FROM admin_user_roles
WHERE admin_user_id = $1
`

func (q *Queries) ListAdminUserRoleByAdminUserId(ctx context.Context, adminUserID pgtype.Int4) ([]AdminUserRole, error) {
	rows, err := q.db.Query(ctx, listAdminUserRoleByAdminUserId, adminUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminUserRole{}
	for rows.Next() {
		var i AdminUserRole
		if err := rows.Scan(&i.AdminUserID, &i.RoleID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminUserRoleByRoleId = `-- name: ListAdminUserRoleByRoleId :many
SELECT admin_user_id, role_id FROM admin_user_roles
WHERE role_id = $1
`

func (q *Queries) ListAdminUserRoleByRoleId(ctx context.Context, roleID pgtype.Int4) ([]AdminUserRole, error) {
	rows, err := q.db.Query(ctx, listAdminUserRoleByRoleId, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminUserRole{}
	for rows.Next() {
		var i AdminUserRole
		if err := rows.Scan(&i.AdminUserID, &i.RoleID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
