// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type AdminUser struct {
	ID             int64  `json:"id"`
	Account        string `json:"account"`
	FullName       string `json:"full_name"`
	HashedPassword string `json:"hashed_password"`
	// must be either 0 or 1
	Status            int32     `json:"status"`
	PasswordChangedAt time.Time `json:"password_changed_at"`
	CreatedAt         time.Time `json:"created_at"`
}

type AdminUserRole struct {
	AdminUserID pgtype.Int4 `json:"admin_user_id"`
	RoleID      pgtype.Int4 `json:"role_id"`
}

type Permission struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type Role struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type RolePermission struct {
	RoleID       pgtype.Int4 `json:"role_id"`
	PermissionID pgtype.Int4 `json:"permission_id"`
}
