// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: order_status.sql

package db

import (
	"context"
)

const createOrderStatus = `-- name: CreateOrderStatus :one
INSERT INTO order_status (
  name
) VALUES (
  $1
) RETURNING id, name
`

func (q *Queries) CreateOrderStatus(ctx context.Context, name string) (OrderStatus, error) {
	row := q.db.QueryRow(ctx, createOrderStatus, name)
	var i OrderStatus
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getOrderStatus = `-- name: GetOrderStatus :one
SELECT id, name FROM order_status
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetOrderStatus(ctx context.Context, id int64) (OrderStatus, error) {
	row := q.db.QueryRow(ctx, getOrderStatus, id)
	var i OrderStatus
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const listOrderStatus = `-- name: ListOrderStatus :many
SELECT id, name FROM order_status
ORDER BY id
`

func (q *Queries) ListOrderStatus(ctx context.Context) ([]OrderStatus, error) {
	rows, err := q.db.Query(ctx, listOrderStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderStatus{}
	for rows.Next() {
		var i OrderStatus
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
