// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: role_permission.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRolePermission = `-- name: CreateRolePermission :one
INSERT INTO role_permissions (
  role_id,
  permission_id
) VALUES (
  $1, $2
) RETURNING role_id, permission_id
`

type CreateRolePermissionParams struct {
	RoleID       pgtype.Int4 `json:"role_id"`
	PermissionID pgtype.Int4 `json:"permission_id"`
}

func (q *Queries) CreateRolePermission(ctx context.Context, arg CreateRolePermissionParams) (RolePermission, error) {
	row := q.db.QueryRow(ctx, createRolePermission, arg.RoleID, arg.PermissionID)
	var i RolePermission
	err := row.Scan(&i.RoleID, &i.PermissionID)
	return i, err
}

const deleteRolePermissionByPermissionId = `-- name: DeleteRolePermissionByPermissionId :exec
DELETE FROM role_permissions
WHERE permission_id = $1
`

func (q *Queries) DeleteRolePermissionByPermissionId(ctx context.Context, permissionID pgtype.Int4) error {
	_, err := q.db.Exec(ctx, deleteRolePermissionByPermissionId, permissionID)
	return err
}

const deleteRolePermissionByRoleId = `-- name: DeleteRolePermissionByRoleId :exec
DELETE FROM role_permissions
WHERE role_id = $1
`

func (q *Queries) DeleteRolePermissionByRoleId(ctx context.Context, roleID pgtype.Int4) error {
	_, err := q.db.Exec(ctx, deleteRolePermissionByRoleId, roleID)
	return err
}

const getRolePermission = `-- name: GetRolePermission :one
SELECT role_id, permission_id FROM role_permissions
WHERE role_id = $1 AND permission_id = $2
LIMIT 1
`

type GetRolePermissionParams struct {
	RoleID       pgtype.Int4 `json:"role_id"`
	PermissionID pgtype.Int4 `json:"permission_id"`
}

func (q *Queries) GetRolePermission(ctx context.Context, arg GetRolePermissionParams) (RolePermission, error) {
	row := q.db.QueryRow(ctx, getRolePermission, arg.RoleID, arg.PermissionID)
	var i RolePermission
	err := row.Scan(&i.RoleID, &i.PermissionID)
	return i, err
}

const listRolePermissionByPermissionId = `-- name: ListRolePermissionByPermissionId :many
SELECT role_id, permission_id FROM role_permissions
WHERE permission_id = $1
`

func (q *Queries) ListRolePermissionByPermissionId(ctx context.Context, permissionID pgtype.Int4) ([]RolePermission, error) {
	rows, err := q.db.Query(ctx, listRolePermissionByPermissionId, permissionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RolePermission{}
	for rows.Next() {
		var i RolePermission
		if err := rows.Scan(&i.RoleID, &i.PermissionID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolePermissionByRoleId = `-- name: ListRolePermissionByRoleId :many
SELECT role_id, permission_id FROM role_permissions
WHERE role_id = $1
`

func (q *Queries) ListRolePermissionByRoleId(ctx context.Context, roleID pgtype.Int4) ([]RolePermission, error) {
	rows, err := q.db.Query(ctx, listRolePermissionByRoleId, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RolePermission{}
	for rows.Next() {
		var i RolePermission
		if err := rows.Scan(&i.RoleID, &i.PermissionID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
