name: Deploy to production CD

on:
  workflow_run:
    workflows:
      - "Deploy to production CI"
    branches: ["main"]
    types:
      - completed

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    env:
      AWS_USER: ${{ secrets.AWS_USER }}
      AWS_SERVER: ${{ secrets.AWS_SERVER }}
      AWS_PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2 # More information on this action can be found below in the 'AWS Credentials' section
        with:
          role-to-assume: arn:aws:iam::617893088694:role/GitHubAction-AssumeRoleWithAction
          aws-region: ap-northeast-1

      - name: COPY PrivateKey
        run: |
          cat "$AWS_PRIVATE_KEY" > private_key.pem
          chmod 400 private_key.pem

      - name: connect SSH to AWS EC2
        run: ssh -o StrictHostKeyChecking=no -i private_key.pem $AWS_USER@$AWS_SERVER "ls -al"
