name: Deploy to production CD

on:
  workflow_run:
    workflows:
      - "Deploy to production CI"
    branches: ["main"]
    types:
      - completed

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    env:
      AWS_USER: ${{ secrets.AWS_USER }}
      AWS_SERVER: ${{ secrets.AWS_SERVER }}
      AWS_PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Connect to AWS EC2
        run: |
          echo "$AWS_PRIVATE_KEY" > private_key && chmod 600 private_key
          scp -o StrictHostKeyChecking=no -i private_key ./docker-compose-production.yml ${AWS_USER}@${AWS_SERVER}:/home/ec2-user
          ssh -o StrictHostKeyChecking=no -i private_key ${AWS_USER}@${AWS_SERVER} "
            docker compose -f docker-compose-production.yml down &&
            docker compose -f docker-compose-production.yml up -d &&
            docker compose ps
          "
