name: Deploy to production CD

on:
  workflow_run:
    workflows:
      - "Deploy to production CI"
    branches: [main]
    types:
      - completed

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    env:
      AWS_URL: 617893088694.dkr.ecr.ap-northeast-1.amazonaws.com/
      CONTAINER_NAME: shopping-mall-go

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2 # More information on this action can be found below in the 'AWS Credentials' section
        with:
          role-to-assume: arn:aws:iam::617893088694:role/GitHubAction-AssumeRoleWithAction
          aws-region: ap-northeast-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Pull AWS ECR images
        run: sudo docker pull $AWS_URL/$CONTAINER_NAME:latest

      - name: Delete Old Docker container
        run: sudo docker rm -f $CONTAINER_NAME || true

      - name: Run Docker container
        run: sudo docker run -d -p 8080:8080 --name $CONTAINER_NAME $AWS_URL/$CONTAINER_NAME:latest
