name: Deploy to production CD

on:
  workflow_run:
    workflows:
      - "Deploy to production CI"
    branches: ["main"]
    types:
      - completed

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    env:
      AWS_URL: 617893088694.dkr.ecr.ap-northeast-1.amazonaws.com
      CONTAINER_NAME: shopping-mall-go

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2 # More information on this action can be found below in the 'AWS Credentials' section
        with:
          role-to-assume: arn:aws:iam::617893088694:role/GitHubAction-AssumeRoleWithAction
          aws-region: ap-northeast-1

      - name: Login to Amazon ECR
        run: aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin $AWS_URL

      - name: Pull AWS ECR images
        run: sudo docker pull $AWS_URL/$CONTAINER_NAME:latest

      - name: Delete Old Docker container
        run: sudo docker rm -f $CONTAINER_NAME || true

      - name: Run Docker container
        run: sudo docker run -d -p 8080:8080 --name $CONTAINER_NAME $AWS_URL/$CONTAINER_NAME:latest
