// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/juker1141/shopping-mall-go/db/sqlc (interfaces: Store)

// Package mockdb is a generated GoMock package.
package mockdb

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	pgtype "github.com/jackc/pgx/v5/pgtype"
	db "github.com/juker1141/shopping-mall-go/db/sqlc"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// CreateAdminUser mocks base method.
func (m *MockStore) CreateAdminUser(arg0 context.Context, arg1 db.CreateAdminUserParams) (db.AdminUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAdminUser", arg0, arg1)
	ret0, _ := ret[0].(db.AdminUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAdminUser indicates an expected call of CreateAdminUser.
func (mr *MockStoreMockRecorder) CreateAdminUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAdminUser", reflect.TypeOf((*MockStore)(nil).CreateAdminUser), arg0, arg1)
}

// CreateAdminUserRole mocks base method.
func (m *MockStore) CreateAdminUserRole(arg0 context.Context, arg1 db.CreateAdminUserRoleParams) (db.AdminUserRole, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAdminUserRole", arg0, arg1)
	ret0, _ := ret[0].(db.AdminUserRole)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAdminUserRole indicates an expected call of CreateAdminUserRole.
func (mr *MockStoreMockRecorder) CreateAdminUserRole(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAdminUserRole", reflect.TypeOf((*MockStore)(nil).CreateAdminUserRole), arg0, arg1)
}

// CreateAdminUserTx mocks base method.
func (m *MockStore) CreateAdminUserTx(arg0 context.Context, arg1 db.CreateAdminUserTxParams) (db.AdminUserTxResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAdminUserTx", arg0, arg1)
	ret0, _ := ret[0].(db.AdminUserTxResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAdminUserTx indicates an expected call of CreateAdminUserTx.
func (mr *MockStoreMockRecorder) CreateAdminUserTx(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAdminUserTx", reflect.TypeOf((*MockStore)(nil).CreateAdminUserTx), arg0, arg1)
}

// CreateCart mocks base method.
func (m *MockStore) CreateCart(arg0 context.Context, arg1 db.CreateCartParams) (db.Cart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCart", arg0, arg1)
	ret0, _ := ret[0].(db.Cart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCart indicates an expected call of CreateCart.
func (mr *MockStoreMockRecorder) CreateCart(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCart", reflect.TypeOf((*MockStore)(nil).CreateCart), arg0, arg1)
}

// CreateCartCoupon mocks base method.
func (m *MockStore) CreateCartCoupon(arg0 context.Context, arg1 db.CreateCartCouponParams) (db.CartCoupon, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCartCoupon", arg0, arg1)
	ret0, _ := ret[0].(db.CartCoupon)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCartCoupon indicates an expected call of CreateCartCoupon.
func (mr *MockStoreMockRecorder) CreateCartCoupon(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCartCoupon", reflect.TypeOf((*MockStore)(nil).CreateCartCoupon), arg0, arg1)
}

// CreateCartProduct mocks base method.
func (m *MockStore) CreateCartProduct(arg0 context.Context, arg1 db.CreateCartProductParams) (db.CartProduct, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCartProduct", arg0, arg1)
	ret0, _ := ret[0].(db.CartProduct)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCartProduct indicates an expected call of CreateCartProduct.
func (mr *MockStoreMockRecorder) CreateCartProduct(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCartProduct", reflect.TypeOf((*MockStore)(nil).CreateCartProduct), arg0, arg1)
}

// CreateCoupon mocks base method.
func (m *MockStore) CreateCoupon(arg0 context.Context, arg1 db.CreateCouponParams) (db.Coupon, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCoupon", arg0, arg1)
	ret0, _ := ret[0].(db.Coupon)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCoupon indicates an expected call of CreateCoupon.
func (mr *MockStoreMockRecorder) CreateCoupon(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCoupon", reflect.TypeOf((*MockStore)(nil).CreateCoupon), arg0, arg1)
}

// CreateGender mocks base method.
func (m *MockStore) CreateGender(arg0 context.Context, arg1 string) (db.Gender, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateGender", arg0, arg1)
	ret0, _ := ret[0].(db.Gender)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateGender indicates an expected call of CreateGender.
func (mr *MockStoreMockRecorder) CreateGender(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGender", reflect.TypeOf((*MockStore)(nil).CreateGender), arg0, arg1)
}

// CreatePermission mocks base method.
func (m *MockStore) CreatePermission(arg0 context.Context, arg1 string) (db.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePermission", arg0, arg1)
	ret0, _ := ret[0].(db.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePermission indicates an expected call of CreatePermission.
func (mr *MockStoreMockRecorder) CreatePermission(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePermission", reflect.TypeOf((*MockStore)(nil).CreatePermission), arg0, arg1)
}

// CreateProduct mocks base method.
func (m *MockStore) CreateProduct(arg0 context.Context, arg1 db.CreateProductParams) (db.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProduct", arg0, arg1)
	ret0, _ := ret[0].(db.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProduct indicates an expected call of CreateProduct.
func (mr *MockStoreMockRecorder) CreateProduct(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProduct", reflect.TypeOf((*MockStore)(nil).CreateProduct), arg0, arg1)
}

// CreateRole mocks base method.
func (m *MockStore) CreateRole(arg0 context.Context, arg1 string) (db.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRole", arg0, arg1)
	ret0, _ := ret[0].(db.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRole indicates an expected call of CreateRole.
func (mr *MockStoreMockRecorder) CreateRole(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRole", reflect.TypeOf((*MockStore)(nil).CreateRole), arg0, arg1)
}

// CreateRolePermission mocks base method.
func (m *MockStore) CreateRolePermission(arg0 context.Context, arg1 db.CreateRolePermissionParams) (db.RolePermission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRolePermission", arg0, arg1)
	ret0, _ := ret[0].(db.RolePermission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRolePermission indicates an expected call of CreateRolePermission.
func (mr *MockStoreMockRecorder) CreateRolePermission(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRolePermission", reflect.TypeOf((*MockStore)(nil).CreateRolePermission), arg0, arg1)
}

// CreateRoleTx mocks base method.
func (m *MockStore) CreateRoleTx(arg0 context.Context, arg1 db.CreateRoleTxParams) (db.RoleTxResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRoleTx", arg0, arg1)
	ret0, _ := ret[0].(db.RoleTxResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRoleTx indicates an expected call of CreateRoleTx.
func (mr *MockStoreMockRecorder) CreateRoleTx(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRoleTx", reflect.TypeOf((*MockStore)(nil).CreateRoleTx), arg0, arg1)
}

// CreateSession mocks base method.
func (m *MockStore) CreateSession(arg0 context.Context, arg1 db.CreateSessionParams) (db.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSession", arg0, arg1)
	ret0, _ := ret[0].(db.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSession indicates an expected call of CreateSession.
func (mr *MockStoreMockRecorder) CreateSession(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockStore)(nil).CreateSession), arg0, arg1)
}

// CreateUser mocks base method.
func (m *MockStore) CreateUser(arg0 context.Context, arg1 db.CreateUserParams) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", arg0, arg1)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockStoreMockRecorder) CreateUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockStore)(nil).CreateUser), arg0, arg1)
}

// DeleteAdminUser mocks base method.
func (m *MockStore) DeleteAdminUser(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAdminUser", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAdminUser indicates an expected call of DeleteAdminUser.
func (mr *MockStoreMockRecorder) DeleteAdminUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAdminUser", reflect.TypeOf((*MockStore)(nil).DeleteAdminUser), arg0, arg1)
}

// DeleteAdminUserRoleByAdminUserId mocks base method.
func (m *MockStore) DeleteAdminUserRoleByAdminUserId(arg0 context.Context, arg1 pgtype.Int4) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAdminUserRoleByAdminUserId", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAdminUserRoleByAdminUserId indicates an expected call of DeleteAdminUserRoleByAdminUserId.
func (mr *MockStoreMockRecorder) DeleteAdminUserRoleByAdminUserId(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAdminUserRoleByAdminUserId", reflect.TypeOf((*MockStore)(nil).DeleteAdminUserRoleByAdminUserId), arg0, arg1)
}

// DeleteAdminUserRoleByRoleId mocks base method.
func (m *MockStore) DeleteAdminUserRoleByRoleId(arg0 context.Context, arg1 pgtype.Int4) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAdminUserRoleByRoleId", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAdminUserRoleByRoleId indicates an expected call of DeleteAdminUserRoleByRoleId.
func (mr *MockStoreMockRecorder) DeleteAdminUserRoleByRoleId(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAdminUserRoleByRoleId", reflect.TypeOf((*MockStore)(nil).DeleteAdminUserRoleByRoleId), arg0, arg1)
}

// DeleteAdminUserTx mocks base method.
func (m *MockStore) DeleteAdminUserTx(arg0 context.Context, arg1 db.DeleteAdminUserTxParams) (db.DeleteAdminUserTxResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAdminUserTx", arg0, arg1)
	ret0, _ := ret[0].(db.DeleteAdminUserTxResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteAdminUserTx indicates an expected call of DeleteAdminUserTx.
func (mr *MockStoreMockRecorder) DeleteAdminUserTx(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAdminUserTx", reflect.TypeOf((*MockStore)(nil).DeleteAdminUserTx), arg0, arg1)
}

// DeleteCart mocks base method.
func (m *MockStore) DeleteCart(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCart", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCart indicates an expected call of DeleteCart.
func (mr *MockStoreMockRecorder) DeleteCart(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCart", reflect.TypeOf((*MockStore)(nil).DeleteCart), arg0, arg1)
}

// DeleteCartCouponByCartId mocks base method.
func (m *MockStore) DeleteCartCouponByCartId(arg0 context.Context, arg1 pgtype.Int4) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCartCouponByCartId", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCartCouponByCartId indicates an expected call of DeleteCartCouponByCartId.
func (mr *MockStoreMockRecorder) DeleteCartCouponByCartId(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCartCouponByCartId", reflect.TypeOf((*MockStore)(nil).DeleteCartCouponByCartId), arg0, arg1)
}

// DeleteCartCouponByCouponId mocks base method.
func (m *MockStore) DeleteCartCouponByCouponId(arg0 context.Context, arg1 pgtype.Int4) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCartCouponByCouponId", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCartCouponByCouponId indicates an expected call of DeleteCartCouponByCouponId.
func (mr *MockStoreMockRecorder) DeleteCartCouponByCouponId(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCartCouponByCouponId", reflect.TypeOf((*MockStore)(nil).DeleteCartCouponByCouponId), arg0, arg1)
}

// DeleteCartProductByCartId mocks base method.
func (m *MockStore) DeleteCartProductByCartId(arg0 context.Context, arg1 pgtype.Int4) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCartProductByCartId", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCartProductByCartId indicates an expected call of DeleteCartProductByCartId.
func (mr *MockStoreMockRecorder) DeleteCartProductByCartId(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCartProductByCartId", reflect.TypeOf((*MockStore)(nil).DeleteCartProductByCartId), arg0, arg1)
}

// DeleteCartProductByProductId mocks base method.
func (m *MockStore) DeleteCartProductByProductId(arg0 context.Context, arg1 pgtype.Int4) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCartProductByProductId", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCartProductByProductId indicates an expected call of DeleteCartProductByProductId.
func (mr *MockStoreMockRecorder) DeleteCartProductByProductId(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCartProductByProductId", reflect.TypeOf((*MockStore)(nil).DeleteCartProductByProductId), arg0, arg1)
}

// DeleteCoupon mocks base method.
func (m *MockStore) DeleteCoupon(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCoupon", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCoupon indicates an expected call of DeleteCoupon.
func (mr *MockStoreMockRecorder) DeleteCoupon(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCoupon", reflect.TypeOf((*MockStore)(nil).DeleteCoupon), arg0, arg1)
}

// DeletePermission mocks base method.
func (m *MockStore) DeletePermission(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePermission", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePermission indicates an expected call of DeletePermission.
func (mr *MockStoreMockRecorder) DeletePermission(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePermission", reflect.TypeOf((*MockStore)(nil).DeletePermission), arg0, arg1)
}

// DeleteProduct mocks base method.
func (m *MockStore) DeleteProduct(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProduct", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProduct indicates an expected call of DeleteProduct.
func (mr *MockStoreMockRecorder) DeleteProduct(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProduct", reflect.TypeOf((*MockStore)(nil).DeleteProduct), arg0, arg1)
}

// DeleteRole mocks base method.
func (m *MockStore) DeleteRole(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRole", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRole indicates an expected call of DeleteRole.
func (mr *MockStoreMockRecorder) DeleteRole(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRole", reflect.TypeOf((*MockStore)(nil).DeleteRole), arg0, arg1)
}

// DeleteRolePermissionByPermissionId mocks base method.
func (m *MockStore) DeleteRolePermissionByPermissionId(arg0 context.Context, arg1 pgtype.Int4) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRolePermissionByPermissionId", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRolePermissionByPermissionId indicates an expected call of DeleteRolePermissionByPermissionId.
func (mr *MockStoreMockRecorder) DeleteRolePermissionByPermissionId(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRolePermissionByPermissionId", reflect.TypeOf((*MockStore)(nil).DeleteRolePermissionByPermissionId), arg0, arg1)
}

// DeleteRolePermissionByRoleId mocks base method.
func (m *MockStore) DeleteRolePermissionByRoleId(arg0 context.Context, arg1 pgtype.Int4) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRolePermissionByRoleId", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRolePermissionByRoleId indicates an expected call of DeleteRolePermissionByRoleId.
func (mr *MockStoreMockRecorder) DeleteRolePermissionByRoleId(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRolePermissionByRoleId", reflect.TypeOf((*MockStore)(nil).DeleteRolePermissionByRoleId), arg0, arg1)
}

// DeleteRoleTx mocks base method.
func (m *MockStore) DeleteRoleTx(arg0 context.Context, arg1 db.DeleteRoleTxParams) (db.DeleteRoleTxResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRoleTx", arg0, arg1)
	ret0, _ := ret[0].(db.DeleteRoleTxResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteRoleTx indicates an expected call of DeleteRoleTx.
func (mr *MockStoreMockRecorder) DeleteRoleTx(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRoleTx", reflect.TypeOf((*MockStore)(nil).DeleteRoleTx), arg0, arg1)
}

// DeleteUser mocks base method.
func (m *MockStore) DeleteUser(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockStoreMockRecorder) DeleteUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockStore)(nil).DeleteUser), arg0, arg1)
}

// GetAdminUser mocks base method.
func (m *MockStore) GetAdminUser(arg0 context.Context, arg1 int64) (db.AdminUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAdminUser", arg0, arg1)
	ret0, _ := ret[0].(db.AdminUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAdminUser indicates an expected call of GetAdminUser.
func (mr *MockStoreMockRecorder) GetAdminUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAdminUser", reflect.TypeOf((*MockStore)(nil).GetAdminUser), arg0, arg1)
}

// GetAdminUserByAccount mocks base method.
func (m *MockStore) GetAdminUserByAccount(arg0 context.Context, arg1 string) (db.AdminUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAdminUserByAccount", arg0, arg1)
	ret0, _ := ret[0].(db.AdminUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAdminUserByAccount indicates an expected call of GetAdminUserByAccount.
func (mr *MockStoreMockRecorder) GetAdminUserByAccount(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAdminUserByAccount", reflect.TypeOf((*MockStore)(nil).GetAdminUserByAccount), arg0, arg1)
}

// GetAdminUserRole mocks base method.
func (m *MockStore) GetAdminUserRole(arg0 context.Context, arg1 db.GetAdminUserRoleParams) (db.AdminUserRole, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAdminUserRole", arg0, arg1)
	ret0, _ := ret[0].(db.AdminUserRole)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAdminUserRole indicates an expected call of GetAdminUserRole.
func (mr *MockStoreMockRecorder) GetAdminUserRole(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAdminUserRole", reflect.TypeOf((*MockStore)(nil).GetAdminUserRole), arg0, arg1)
}

// GetAdminUsersCount mocks base method.
func (m *MockStore) GetAdminUsersCount(arg0 context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAdminUsersCount", arg0)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAdminUsersCount indicates an expected call of GetAdminUsersCount.
func (mr *MockStoreMockRecorder) GetAdminUsersCount(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAdminUsersCount", reflect.TypeOf((*MockStore)(nil).GetAdminUsersCount), arg0)
}

// GetCart mocks base method.
func (m *MockStore) GetCart(arg0 context.Context, arg1 int64) (db.Cart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCart", arg0, arg1)
	ret0, _ := ret[0].(db.Cart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCart indicates an expected call of GetCart.
func (mr *MockStoreMockRecorder) GetCart(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCart", reflect.TypeOf((*MockStore)(nil).GetCart), arg0, arg1)
}

// GetCartByOwner mocks base method.
func (m *MockStore) GetCartByOwner(arg0 context.Context, arg1 pgtype.Text) (db.Cart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCartByOwner", arg0, arg1)
	ret0, _ := ret[0].(db.Cart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCartByOwner indicates an expected call of GetCartByOwner.
func (mr *MockStoreMockRecorder) GetCartByOwner(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCartByOwner", reflect.TypeOf((*MockStore)(nil).GetCartByOwner), arg0, arg1)
}

// GetCartCoupon mocks base method.
func (m *MockStore) GetCartCoupon(arg0 context.Context, arg1 db.GetCartCouponParams) (db.CartCoupon, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCartCoupon", arg0, arg1)
	ret0, _ := ret[0].(db.CartCoupon)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCartCoupon indicates an expected call of GetCartCoupon.
func (mr *MockStoreMockRecorder) GetCartCoupon(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCartCoupon", reflect.TypeOf((*MockStore)(nil).GetCartCoupon), arg0, arg1)
}

// GetCartProduct mocks base method.
func (m *MockStore) GetCartProduct(arg0 context.Context, arg1 db.GetCartProductParams) (db.CartProduct, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCartProduct", arg0, arg1)
	ret0, _ := ret[0].(db.CartProduct)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCartProduct indicates an expected call of GetCartProduct.
func (mr *MockStoreMockRecorder) GetCartProduct(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCartProduct", reflect.TypeOf((*MockStore)(nil).GetCartProduct), arg0, arg1)
}

// GetCoupon mocks base method.
func (m *MockStore) GetCoupon(arg0 context.Context, arg1 int64) (db.Coupon, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCoupon", arg0, arg1)
	ret0, _ := ret[0].(db.Coupon)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCoupon indicates an expected call of GetCoupon.
func (mr *MockStoreMockRecorder) GetCoupon(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCoupon", reflect.TypeOf((*MockStore)(nil).GetCoupon), arg0, arg1)
}

// GetGender mocks base method.
func (m *MockStore) GetGender(arg0 context.Context, arg1 int64) (db.Gender, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGender", arg0, arg1)
	ret0, _ := ret[0].(db.Gender)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGender indicates an expected call of GetGender.
func (mr *MockStoreMockRecorder) GetGender(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGender", reflect.TypeOf((*MockStore)(nil).GetGender), arg0, arg1)
}

// GetPermission mocks base method.
func (m *MockStore) GetPermission(arg0 context.Context, arg1 int64) (db.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPermission", arg0, arg1)
	ret0, _ := ret[0].(db.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPermission indicates an expected call of GetPermission.
func (mr *MockStoreMockRecorder) GetPermission(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPermission", reflect.TypeOf((*MockStore)(nil).GetPermission), arg0, arg1)
}

// GetProduct mocks base method.
func (m *MockStore) GetProduct(arg0 context.Context, arg1 int64) (db.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProduct", arg0, arg1)
	ret0, _ := ret[0].(db.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProduct indicates an expected call of GetProduct.
func (mr *MockStoreMockRecorder) GetProduct(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProduct", reflect.TypeOf((*MockStore)(nil).GetProduct), arg0, arg1)
}

// GetProductsCount mocks base method.
func (m *MockStore) GetProductsCount(arg0 context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductsCount", arg0)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductsCount indicates an expected call of GetProductsCount.
func (mr *MockStoreMockRecorder) GetProductsCount(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductsCount", reflect.TypeOf((*MockStore)(nil).GetProductsCount), arg0)
}

// GetRole mocks base method.
func (m *MockStore) GetRole(arg0 context.Context, arg1 int64) (db.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRole", arg0, arg1)
	ret0, _ := ret[0].(db.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRole indicates an expected call of GetRole.
func (mr *MockStoreMockRecorder) GetRole(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRole", reflect.TypeOf((*MockStore)(nil).GetRole), arg0, arg1)
}

// GetRolePermission mocks base method.
func (m *MockStore) GetRolePermission(arg0 context.Context, arg1 db.GetRolePermissionParams) (db.RolePermission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRolePermission", arg0, arg1)
	ret0, _ := ret[0].(db.RolePermission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRolePermission indicates an expected call of GetRolePermission.
func (mr *MockStoreMockRecorder) GetRolePermission(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRolePermission", reflect.TypeOf((*MockStore)(nil).GetRolePermission), arg0, arg1)
}

// GetRolesCount mocks base method.
func (m *MockStore) GetRolesCount(arg0 context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRolesCount", arg0)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRolesCount indicates an expected call of GetRolesCount.
func (mr *MockStoreMockRecorder) GetRolesCount(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRolesCount", reflect.TypeOf((*MockStore)(nil).GetRolesCount), arg0)
}

// GetSesstion mocks base method.
func (m *MockStore) GetSesstion(arg0 context.Context, arg1 uuid.UUID) (db.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSesstion", arg0, arg1)
	ret0, _ := ret[0].(db.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSesstion indicates an expected call of GetSesstion.
func (mr *MockStoreMockRecorder) GetSesstion(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSesstion", reflect.TypeOf((*MockStore)(nil).GetSesstion), arg0, arg1)
}

// GetUser mocks base method.
func (m *MockStore) GetUser(arg0 context.Context, arg1 int64) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", arg0, arg1)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockStoreMockRecorder) GetUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockStore)(nil).GetUser), arg0, arg1)
}

// GetUserByAccount mocks base method.
func (m *MockStore) GetUserByAccount(arg0 context.Context, arg1 string) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByAccount", arg0, arg1)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByAccount indicates an expected call of GetUserByAccount.
func (mr *MockStoreMockRecorder) GetUserByAccount(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByAccount", reflect.TypeOf((*MockStore)(nil).GetUserByAccount), arg0, arg1)
}

// GetUsersCount mocks base method.
func (m *MockStore) GetUsersCount(arg0 context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsersCount", arg0)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsersCount indicates an expected call of GetUsersCount.
func (mr *MockStoreMockRecorder) GetUsersCount(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersCount", reflect.TypeOf((*MockStore)(nil).GetUsersCount), arg0)
}

// ListAdminUserRoleByAdminUserId mocks base method.
func (m *MockStore) ListAdminUserRoleByAdminUserId(arg0 context.Context, arg1 pgtype.Int4) ([]db.AdminUserRole, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAdminUserRoleByAdminUserId", arg0, arg1)
	ret0, _ := ret[0].([]db.AdminUserRole)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAdminUserRoleByAdminUserId indicates an expected call of ListAdminUserRoleByAdminUserId.
func (mr *MockStoreMockRecorder) ListAdminUserRoleByAdminUserId(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAdminUserRoleByAdminUserId", reflect.TypeOf((*MockStore)(nil).ListAdminUserRoleByAdminUserId), arg0, arg1)
}

// ListAdminUserRoleByRoleId mocks base method.
func (m *MockStore) ListAdminUserRoleByRoleId(arg0 context.Context, arg1 pgtype.Int4) ([]db.AdminUserRole, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAdminUserRoleByRoleId", arg0, arg1)
	ret0, _ := ret[0].([]db.AdminUserRole)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAdminUserRoleByRoleId indicates an expected call of ListAdminUserRoleByRoleId.
func (mr *MockStoreMockRecorder) ListAdminUserRoleByRoleId(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAdminUserRoleByRoleId", reflect.TypeOf((*MockStore)(nil).ListAdminUserRoleByRoleId), arg0, arg1)
}

// ListAdminUsers mocks base method.
func (m *MockStore) ListAdminUsers(arg0 context.Context, arg1 db.ListAdminUsersParams) ([]db.AdminUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAdminUsers", arg0, arg1)
	ret0, _ := ret[0].([]db.AdminUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAdminUsers indicates an expected call of ListAdminUsers.
func (mr *MockStoreMockRecorder) ListAdminUsers(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAdminUsers", reflect.TypeOf((*MockStore)(nil).ListAdminUsers), arg0, arg1)
}

// ListCartCouponByCartId mocks base method.
func (m *MockStore) ListCartCouponByCartId(arg0 context.Context, arg1 pgtype.Int4) ([]db.CartCoupon, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCartCouponByCartId", arg0, arg1)
	ret0, _ := ret[0].([]db.CartCoupon)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCartCouponByCartId indicates an expected call of ListCartCouponByCartId.
func (mr *MockStoreMockRecorder) ListCartCouponByCartId(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCartCouponByCartId", reflect.TypeOf((*MockStore)(nil).ListCartCouponByCartId), arg0, arg1)
}

// ListCartCouponByCouponId mocks base method.
func (m *MockStore) ListCartCouponByCouponId(arg0 context.Context, arg1 pgtype.Int4) ([]db.CartCoupon, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCartCouponByCouponId", arg0, arg1)
	ret0, _ := ret[0].([]db.CartCoupon)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCartCouponByCouponId indicates an expected call of ListCartCouponByCouponId.
func (mr *MockStoreMockRecorder) ListCartCouponByCouponId(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCartCouponByCouponId", reflect.TypeOf((*MockStore)(nil).ListCartCouponByCouponId), arg0, arg1)
}

// ListCartProductByCartId mocks base method.
func (m *MockStore) ListCartProductByCartId(arg0 context.Context, arg1 pgtype.Int4) ([]db.CartProduct, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCartProductByCartId", arg0, arg1)
	ret0, _ := ret[0].([]db.CartProduct)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCartProductByCartId indicates an expected call of ListCartProductByCartId.
func (mr *MockStoreMockRecorder) ListCartProductByCartId(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCartProductByCartId", reflect.TypeOf((*MockStore)(nil).ListCartProductByCartId), arg0, arg1)
}

// ListCartProductByProductId mocks base method.
func (m *MockStore) ListCartProductByProductId(arg0 context.Context, arg1 pgtype.Int4) ([]db.CartProduct, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCartProductByProductId", arg0, arg1)
	ret0, _ := ret[0].([]db.CartProduct)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCartProductByProductId indicates an expected call of ListCartProductByProductId.
func (mr *MockStoreMockRecorder) ListCartProductByProductId(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCartProductByProductId", reflect.TypeOf((*MockStore)(nil).ListCartProductByProductId), arg0, arg1)
}

// ListCoupons mocks base method.
func (m *MockStore) ListCoupons(arg0 context.Context, arg1 db.ListCouponsParams) ([]db.Coupon, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCoupons", arg0, arg1)
	ret0, _ := ret[0].([]db.Coupon)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCoupons indicates an expected call of ListCoupons.
func (mr *MockStoreMockRecorder) ListCoupons(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCoupons", reflect.TypeOf((*MockStore)(nil).ListCoupons), arg0, arg1)
}

// ListGenders mocks base method.
func (m *MockStore) ListGenders(arg0 context.Context) ([]db.Gender, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListGenders", arg0)
	ret0, _ := ret[0].([]db.Gender)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListGenders indicates an expected call of ListGenders.
func (mr *MockStoreMockRecorder) ListGenders(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListGenders", reflect.TypeOf((*MockStore)(nil).ListGenders), arg0)
}

// ListPermissions mocks base method.
func (m *MockStore) ListPermissions(arg0 context.Context, arg1 db.ListPermissionsParams) ([]db.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPermissions", arg0, arg1)
	ret0, _ := ret[0].([]db.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPermissions indicates an expected call of ListPermissions.
func (mr *MockStoreMockRecorder) ListPermissions(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPermissions", reflect.TypeOf((*MockStore)(nil).ListPermissions), arg0, arg1)
}

// ListPermissionsForAdminUser mocks base method.
func (m *MockStore) ListPermissionsForAdminUser(arg0 context.Context, arg1 int64) ([]db.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPermissionsForAdminUser", arg0, arg1)
	ret0, _ := ret[0].([]db.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPermissionsForAdminUser indicates an expected call of ListPermissionsForAdminUser.
func (mr *MockStoreMockRecorder) ListPermissionsForAdminUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPermissionsForAdminUser", reflect.TypeOf((*MockStore)(nil).ListPermissionsForAdminUser), arg0, arg1)
}

// ListPermissionsForRole mocks base method.
func (m *MockStore) ListPermissionsForRole(arg0 context.Context, arg1 int64) ([]db.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPermissionsForRole", arg0, arg1)
	ret0, _ := ret[0].([]db.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPermissionsForRole indicates an expected call of ListPermissionsForRole.
func (mr *MockStoreMockRecorder) ListPermissionsForRole(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPermissionsForRole", reflect.TypeOf((*MockStore)(nil).ListPermissionsForRole), arg0, arg1)
}

// ListPermissionsIDByAccount mocks base method.
func (m *MockStore) ListPermissionsIDByAccount(arg0 context.Context, arg1 string) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPermissionsIDByAccount", arg0, arg1)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPermissionsIDByAccount indicates an expected call of ListPermissionsIDByAccount.
func (mr *MockStoreMockRecorder) ListPermissionsIDByAccount(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPermissionsIDByAccount", reflect.TypeOf((*MockStore)(nil).ListPermissionsIDByAccount), arg0, arg1)
}

// ListProducts mocks base method.
func (m *MockStore) ListProducts(arg0 context.Context, arg1 db.ListProductsParams) ([]db.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProducts", arg0, arg1)
	ret0, _ := ret[0].([]db.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProducts indicates an expected call of ListProducts.
func (mr *MockStoreMockRecorder) ListProducts(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProducts", reflect.TypeOf((*MockStore)(nil).ListProducts), arg0, arg1)
}

// ListRolePermissionByPermissionId mocks base method.
func (m *MockStore) ListRolePermissionByPermissionId(arg0 context.Context, arg1 pgtype.Int4) ([]db.RolePermission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRolePermissionByPermissionId", arg0, arg1)
	ret0, _ := ret[0].([]db.RolePermission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRolePermissionByPermissionId indicates an expected call of ListRolePermissionByPermissionId.
func (mr *MockStoreMockRecorder) ListRolePermissionByPermissionId(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRolePermissionByPermissionId", reflect.TypeOf((*MockStore)(nil).ListRolePermissionByPermissionId), arg0, arg1)
}

// ListRolePermissionByRoleId mocks base method.
func (m *MockStore) ListRolePermissionByRoleId(arg0 context.Context, arg1 pgtype.Int4) ([]db.RolePermission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRolePermissionByRoleId", arg0, arg1)
	ret0, _ := ret[0].([]db.RolePermission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRolePermissionByRoleId indicates an expected call of ListRolePermissionByRoleId.
func (mr *MockStoreMockRecorder) ListRolePermissionByRoleId(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRolePermissionByRoleId", reflect.TypeOf((*MockStore)(nil).ListRolePermissionByRoleId), arg0, arg1)
}

// ListRoles mocks base method.
func (m *MockStore) ListRoles(arg0 context.Context, arg1 db.ListRolesParams) ([]db.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRoles", arg0, arg1)
	ret0, _ := ret[0].([]db.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRoles indicates an expected call of ListRoles.
func (mr *MockStoreMockRecorder) ListRoles(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRoles", reflect.TypeOf((*MockStore)(nil).ListRoles), arg0, arg1)
}

// ListRolesForAdminUser mocks base method.
func (m *MockStore) ListRolesForAdminUser(arg0 context.Context, arg1 int64) ([]db.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRolesForAdminUser", arg0, arg1)
	ret0, _ := ret[0].([]db.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRolesForAdminUser indicates an expected call of ListRolesForAdminUser.
func (mr *MockStoreMockRecorder) ListRolesForAdminUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRolesForAdminUser", reflect.TypeOf((*MockStore)(nil).ListRolesForAdminUser), arg0, arg1)
}

// ListUsers mocks base method.
func (m *MockStore) ListUsers(arg0 context.Context, arg1 db.ListUsersParams) ([]db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsers", arg0, arg1)
	ret0, _ := ret[0].([]db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUsers indicates an expected call of ListUsers.
func (mr *MockStoreMockRecorder) ListUsers(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsers", reflect.TypeOf((*MockStore)(nil).ListUsers), arg0, arg1)
}

// UpdateAdminUser mocks base method.
func (m *MockStore) UpdateAdminUser(arg0 context.Context, arg1 db.UpdateAdminUserParams) (db.AdminUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAdminUser", arg0, arg1)
	ret0, _ := ret[0].(db.AdminUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAdminUser indicates an expected call of UpdateAdminUser.
func (mr *MockStoreMockRecorder) UpdateAdminUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAdminUser", reflect.TypeOf((*MockStore)(nil).UpdateAdminUser), arg0, arg1)
}

// UpdateAdminUserTx mocks base method.
func (m *MockStore) UpdateAdminUserTx(arg0 context.Context, arg1 db.UpdateAdminUserTxParams) (db.AdminUserTxResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAdminUserTx", arg0, arg1)
	ret0, _ := ret[0].(db.AdminUserTxResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAdminUserTx indicates an expected call of UpdateAdminUserTx.
func (mr *MockStoreMockRecorder) UpdateAdminUserTx(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAdminUserTx", reflect.TypeOf((*MockStore)(nil).UpdateAdminUserTx), arg0, arg1)
}

// UpdateCart mocks base method.
func (m *MockStore) UpdateCart(arg0 context.Context, arg1 db.UpdateCartParams) (db.Cart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCart", arg0, arg1)
	ret0, _ := ret[0].(db.Cart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCart indicates an expected call of UpdateCart.
func (mr *MockStoreMockRecorder) UpdateCart(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCart", reflect.TypeOf((*MockStore)(nil).UpdateCart), arg0, arg1)
}

// UpdateCartProduct mocks base method.
func (m *MockStore) UpdateCartProduct(arg0 context.Context, arg1 db.UpdateCartProductParams) (db.CartProduct, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCartProduct", arg0, arg1)
	ret0, _ := ret[0].(db.CartProduct)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCartProduct indicates an expected call of UpdateCartProduct.
func (mr *MockStoreMockRecorder) UpdateCartProduct(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCartProduct", reflect.TypeOf((*MockStore)(nil).UpdateCartProduct), arg0, arg1)
}

// UpdateCoupon mocks base method.
func (m *MockStore) UpdateCoupon(arg0 context.Context, arg1 db.UpdateCouponParams) (db.Coupon, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCoupon", arg0, arg1)
	ret0, _ := ret[0].(db.Coupon)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCoupon indicates an expected call of UpdateCoupon.
func (mr *MockStoreMockRecorder) UpdateCoupon(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCoupon", reflect.TypeOf((*MockStore)(nil).UpdateCoupon), arg0, arg1)
}

// UpdatePermission mocks base method.
func (m *MockStore) UpdatePermission(arg0 context.Context, arg1 db.UpdatePermissionParams) (db.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePermission", arg0, arg1)
	ret0, _ := ret[0].(db.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePermission indicates an expected call of UpdatePermission.
func (mr *MockStoreMockRecorder) UpdatePermission(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePermission", reflect.TypeOf((*MockStore)(nil).UpdatePermission), arg0, arg1)
}

// UpdateProduct mocks base method.
func (m *MockStore) UpdateProduct(arg0 context.Context, arg1 db.UpdateProductParams) (db.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProduct", arg0, arg1)
	ret0, _ := ret[0].(db.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateProduct indicates an expected call of UpdateProduct.
func (mr *MockStoreMockRecorder) UpdateProduct(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProduct", reflect.TypeOf((*MockStore)(nil).UpdateProduct), arg0, arg1)
}

// UpdateRole mocks base method.
func (m *MockStore) UpdateRole(arg0 context.Context, arg1 db.UpdateRoleParams) (db.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRole", arg0, arg1)
	ret0, _ := ret[0].(db.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateRole indicates an expected call of UpdateRole.
func (mr *MockStoreMockRecorder) UpdateRole(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRole", reflect.TypeOf((*MockStore)(nil).UpdateRole), arg0, arg1)
}

// UpdateRoleTx mocks base method.
func (m *MockStore) UpdateRoleTx(arg0 context.Context, arg1 db.UpdateRoleTxParams) (db.RoleTxResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRoleTx", arg0, arg1)
	ret0, _ := ret[0].(db.RoleTxResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateRoleTx indicates an expected call of UpdateRoleTx.
func (mr *MockStoreMockRecorder) UpdateRoleTx(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRoleTx", reflect.TypeOf((*MockStore)(nil).UpdateRoleTx), arg0, arg1)
}

// UpdateUser mocks base method.
func (m *MockStore) UpdateUser(arg0 context.Context, arg1 db.UpdateUserParams) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", arg0, arg1)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockStoreMockRecorder) UpdateUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockStore)(nil).UpdateUser), arg0, arg1)
}
